# Generated by Django 4.0.5 on 2022-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='additional',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='example',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='placeholder',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(),
        ),
    ]
