# Generated by Django 4.0.5 on 2022-06-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proekt', '0002_alter_example_additional_alter_example_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='code',
            field=models.TextField(default='haha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
