# Generated by Django 4.0.5 on 2022-06-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proekt', '0004_alter_example_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Proekt.lecture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='additional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
